# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-03 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarkici', models.CharField(max_length=250)),
                ('album_basligi', models.CharField(max_length=250)),
                ('tur', models.CharField(max_length=250)),
                ('album_logo', models.FileField(upload_to='')),
                ('favoriler', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sarki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarki_basligi', models.CharField(max_length=250)),
                ('ses_dosyalari', models.FileField(default='', upload_to='')),
                ('favoriler', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='single.Album')),
            ],
        ),
    ]
